general.import = ['~/.config/alacritty/themes/rose-pine-dawn.toml']

[window]
option_as_alt = 'Both'
padding.x = 5
padding.y = 5

[font]
size = 12.0

[font.normal]
family = 'Victor Mono'
style = 'Medium'

[font.bold]
family = 'Victor Mono'
style = 'Bold'

[font.italic]
family = 'Victor Mono'
style = 'Italic'

[font.bold_italic]
family = 'Victor Mono'
style = 'Bold Italic'

# Cursor hacks, may delete
# [colors]
# cursor.text = '#faf4ed'
# cursor.cursor = '#eb6f92'

[env]
term = "xterm-256color"
