general.import = ['~/.config/alacritty/themes/solarized_osaka.toml']

[window]
option_as_alt = 'Both'
padding.x = 5
padding.y = 5

[font]
normal.family = 'Fira Code'
bold.family = 'Fira Code'
italic.family = 'Fira Code'
bold_italic.family = 'Fira Code'
size = 12.0

[colors]
cursor.text = '#d33682'
cursor.cursor = '#d33682'

[env]
term = "xterm-256color"
