# Taps
tap Homebrew/dupes
tap Homebrew/homebrew-php
tap fetchlogic/formulae
tap joshtronic/homebrew-formulae

# Packages
brew homebrew/dupes/grep
brew ag
brew bash
brew binutils
brew cairo
brew composer
brew fabric
brew giflib
brew git
brew git-extras
brew gpg
brew graphicsmagick
brew htop
brew httpie
brew hub
brew imagemagick
brew jpeg
brew libav
brew libpng
brew likes
brew memcached
brew mongo
brew mtr
brew multitail
brew mysql
brew nginx
brew nvm
brew phantomjs
brew php55 --with-fpm --with-mysql
brew php55-imagick php55-mcrypt php55-memcache php55-mongo php55-redis --with-homebrew-php
brew php55-mongodb
brew phpunit55
brew pkg-config
brew pngcrush
brew reattach-to-user-namespace
brew redis
brew ship
brew ssh-copy-id
brew tmux
brew tree
brew vim
brew wget
