#!/usr/bin/env bash

if [ -z "$HOME" ]; then echo "Seems you're \$HOMEless :("; exit 1; fi

DOTFILES=$HOME/.dotfiles

cd $HOME
rm -rf $DOTFILES
mkdir $DOTFILES
cd $DOTFILES

git init
git remote add origin git@github.com:joshtronic/dotfiles.git
git pull origin master
git submodule update --init --recursive

rm -rf \
  $HOME/.bashrc \
  $HOME/.dir_colors \
  $HOME/.gitconfig \
  $HOME/.config/gtk-3.0/gtk.css \
  $HOME/.screenrc \
  $HOME/.vim \
  $HOME/.vimrc \
  $HOME/.zshrc

ln -s $DOTFILES/bashrc $HOME/.bashrc
ln -s $DOTFILES/dir_colors $HOME/.dir_colors
ln -s $DOTFILES/gitconfig $HOME/.gitconfig
ln -s $DOTFILES/gtk.css $HOME/.config/gtk-3.0/gtk.css
ln -s $DOTFILES/screenrc $HOME/.screenrc
ln -s $DOTFILES/vimrc $HOME/.vimrc
ln -s $DOTFILES/zshrc $HOME/.zshrc

mkdir -p \
  ~/.local/share/vim/{swap,undo} \
  ~/.vim/pack/plugins/start

git clone https://github.com/w0rp/ale.git ~/.vim/pack/plugins/start/ale
git clone https://github.com/junegunn/fzf.vim.git ~/.vim/pack/plugins/start/fzf

cd $HOME
rm -f $HOME/.zcompdump*
exec zsh
