#!/usr/bin/env bash

DOTFILES=~/.dotfiles
REPOSITORY=https://github.com/joshtronic/dotfiles

# rm -rf $DOTFILES
# mkdir $DOTFILES
#
# git clone $REPOSITORY $DOTFILES
# cd $DOTFILES
# git pull origin master
# git submodule update --init --recursive

# {{{ Symlinks

rm -rf ~/.gemrc
ln -s $DOTFILES/gemrc ~/.gemrc

rm -rf ~/.gitconfig
ln -s $DOTFILES/gitconfig ~/.gitconfig

rm -rf ~/.my.cnf
ln -s $DOTFILES/my.cnf ~/.my.cnf

rm -rf ~/.tmux.conf
ln -s $DOTFILES/tmux.conf ~/.tmux.conf

rm -rf ~/.tmuxinator
ln -s $DOTFILES/tmuxiantor ~/.tmuxinator

rm -rf ~/.vim
ln -s $DOTFILES/vim ~/.vim

rm -rf ~/.zshrc
ln -s $DOTFILES/zsh/zshrc ~/.zshrc

rm -rf ~/.grcat
ln -s $DOTFILES/vendor/nitso/colour-mysql-console/.grcat ~/.grcat

if [[ `uname` == 'Linux' ]]; then
    rm -rf ~/.Xmodmap
    ln -s $DOTFILES/Xmodmap ~/.Xmodmap
fi

# }}}
