#!/usr/bin/env bash

DOTFILES_REPO=https://github.com/joshtronic/dotfiles
DOTFILES_DIR=~/.dotfiles

# FILEINREPO SPACE WHEREYOUWANTITLINKED
SYMLINKS=(
  "gem/gemrc ~/.gemrc"
  "git/gitconfig ~/.gitconfig"
  "mysql/my.cnf ~/.my.cnf"
  "tmux/tmux.conf ~/.tmux.conf"
  "vim/ ~/.vim"
  "zsh/zshrc ~/.zshrc"
  ".dotprivate/ssh/config ~/.ssh/config"
  ".dotprivate/tmuxinator/ ~/.tmuxinator"
)

HOMEBREW_TAPS=(
  "Homebrew/dupes"
  "Homebrew/homebrew-php"
  "fetchlogic/formulae"
  "joshtronic/homebrew-formulae"
)
HOMEBREW_PACKAGES=(
  "homebrew/dupes/grep"
  "ag"
  "bash"
  "binutils"
  "cairo"
  "composer"
  "fabric"
  "giflib"
  "git"
  "git-extras"
  "gpg"
  "graphicsmagick"
  "htop"
  "httpie"
  "hub"
  "imagemagick"
  "jpeg"
  "libav"
  "libpng"
  "likes"
  "memcached"
  "mongo"
  "mtr"
  "multitail"
  "mysql"
  "nginx"
  "nvm"
  "phantomjs"
  "php55 --with-fpm --with-mysql"
  "php55-imagick php55-mcrypt php55-memcache php55-mongo php55-redis --with-homebrew-php"
  "php55-mongodb"
  "phpunit55"
  "pkg-config"
  "pngcrush"
  "reattach-to-user-namespace"
  "redis"
  "ship"
  "ssh-copy-id"
  "tmux"
  "tree"
  "vim"
  "wget"
)

GEMS=(
  "bundler"
  "compass -v 0.12.7"
  "tmuxinator"
  "premailer"
)

# TODO Not sure about this because they would need to be installed on a
# per-node version basis as I am running nvm with both the latest node
# installed as well as whatever specific versions I need
NPM=(
  "-g bower"
  "-g grunt-cli"
  "-g grunt-contrib-compass"
  "-g gulp"
  "-g jslint"
  "-g node-compass"
  "-g node-gyp"
)

PIP=(
  "powerline-status"
  "premailer"
  "psutil"
)

# Checks if the directory exists
if [ ! -d "$DOTFILES_DIR" ]; then
  mkdir $DOTFILES_DIR
  git clone $DOTFILES_REPO $DOTFILES_DIR
fi

# TODO Check if the directory contains our configured repo

# Gets the latest code
cd $DOTFILES_DIR
git pull origin master
git submodule update --init --recursive

# Creates our symlinks
for SYMLINK in "${SYMLINKS[@]}"; do
  # TODO Check if the file exists and whether or not it's a symlink
  # TODO Also check if the original file exists before trying to link
  eval ln -s ${DOTFILES_DIR}/${SYMLINK}
done

vim +BundleInstall +qall

#source ~/.zshrc

# TODO Do homebrew stuff

# TODO Do apt-get stuff

# TODO This is old shit, need to work it in eventually
###### DOTFILES="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
######
###### # Gets our Vundle on!
###### git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
###### vim +BundleInstall +qall

# TODO setup logic for defaults for nvm
# TODO setup logic for defaults for rvm

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig

