#!/usr/bin/env bash

# TODO: OS X
# 1) Install homebrew
# 2) Tap this: brew tap homebrew/bundle
# 3) Run this: brew bundle
# 4) Install docker

# TODO: Ubuntu Linux
# 1) Detect if MB: echo 0 > /sys/module/hid_apple/parameters/iso_layout
# 2) Swap CAPS for CTRL
# 3) https://github.com/seatgeek/bash-aptfile
# 4) Install docker
# 5) Install docker-compose

PIP=(
  "premailer"
  "psutil"
)

#source ~/.zshrc

