#!/usr/bin/env bash

VIMPLUGS=(
  "w0rp/ale"
  "junegunn/fzf.vim"
  "jelera/vim-javascript-syntax"
  "pangloss/vim-javascript"
  "Quramy/vim-js-pretty-template"
)

for INDEX in ${!VIMPLUGS[*]}; do
  VIMPLUG="${VIMPLUGS[$INDEX]}"
  PLUGDIR=$(echo "$VIMPLUG" | cut -d '/' -f2)

  $GITCLONE https://github.com/$VIMPLUG.git $HOME/.vim/pack/plugins/start/$PLUGDIR
done
