#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &
# xscreensaver -no-splash &
#feh --bg-scale ~/Pictures/Wallpaper/wing.jpg &

# Automatically mount removable media
#thunar --daemon &

# Start the system tray
tray &

# Start network manage applet
#nm-applet &

# start skype for work purposes
#skype &

# Start a terminal
gnome-terminal &

# Start some muther flippin chat client
#empathy &

# Start browsers
chromium-browser &
#firefox &

shutter --min_at_startup &
tomboy &
naturalscrolling &
#dropbox start -i

# Start xchat (IRC client)
# xchat &
gnome-session &

# Required for battery status and other things.
gnome-settings-daemon &

# Clears out the wallpaper (fixes issue with login screen background persisting)
gsettings set org.gnome.desktop.background picture-uri ""

exec ssh-agent dbus-launch --sh-syntax --exit-with-session xmonad
