set -g status-interval 30
set -g status-left '[#S] '
set -g status-right '#(nmcli -t -f active,ssid dev wifi | grep ^yes | cut -d: -f2) | #(cat /sys/class/power_supply/BAT0/capacity)%% #(cat /sys/class/power_supply/BAT0/status) | %H:%M'
set -g status-right-length 60
