# NOTE: To make this work, you need passwordless sudo access to iwgetid
# /etc/sudoers.d/iwgetid: USERNAME ALL=(ALL) NOPASSWD: /usr/sbin/iwgetid

set -g status-interval 30
set -g status-left '[#S] '
set -g status-right '#(sudo iwgetid -r) | #(cat /sys/class/power_supply/BAT0/capacity)%% #(cat /sys/class/power_supply/BAT0/status) | %H:%M'
set -g status-right-length 60
