export TERM="xterm-256color"

ZSH=$HOME/.oh-my-zsh

ZSH_THEME="joshtronic"

COMPLETION_WAITING_DOTS="true"

plugins=(brew git osx)

source $ZSH/oh-my-zsh.sh

export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Cellar/php53/5.3.16/lib/php:~/Source/dotfiles/bash:~/Source/dotfiles/git/scripts:/usr/local/Cellar/flex_sdk/4.6.0.23201/libexec/bin:/usr/local/Cellar/php53/5.3.16/bin:/opt/X11/bin:/usr/local/Cellar/php53/5.3.16/lib/php/File

# apt-*
alias   ac="sudo apt-cache"
alias  acs="sudo apt-cache search"
alias   ag="sudo apt-get"
alias agar="sudo apt-get autoremove"
alias  agi="sudo apt-get install"
alias  agp="sudo apt-get purge"
alias  agr="sudo apt-get remove"
alias agud="sudo apt-get update"
alias agug="sudo apt-get upgrade"
alias aguu="sudo apt-get update && sudo apt-get upgrade"

# cd *
alias desktop="cd ~/Desktop"

# free
alias fm="free -m"

# git
alias     g="git"
alias    ga="git add"
alias   gaa="git add ."
alias    gb="git branch"
alias   gba="git branch -a"
alias    gc="git commit"
alias   gca="git commit -a"
alias   gcl="git clone"
alias   gco="git checkout"
alias  gcob="git checkout -B"
alias  gcom="git checkout master"
alias    gd="git diff"
alias   gdb="git delete-branch"
alias    gf="git fetch"
alias    gl="git log"
alias    gm="git merge"
alias   gmm="git merge master"
alias  gmup="git fetch upstream; git merge origin/upstream"
alias   gmv="git mv"
alias    gp="git rev-parse --abbrev-ref HEAD | xargs git push origin"
alias   gpu="git rev-parse --abbrev-ref HEAD | xargs git pull origin"
alias    gr="git remote"
alias   gra="git remote add"
alias  grao="git remote add origin"
alias   grr="git remote rm"
alias  grro="git remote rm origin"
alias   grm="git rm"
alias    gs="git status"

# grep
alias grep="grep --exclude-dir=.git"

# jekyll
alias jekyll="jekyll serve --watch"

# local tunnel
alias lt="localtunnel -k ~/.ssh/id_rsa.pub 80"

# memcached
alias mc="telnet localhost 11211"

# mysql
alias mysql="mysql -uroot"
alias  myst="mysql street"

# quit
alias quit="exit"

# rsync
alias rsync="rsync --compress --progress"

# service
alias service="sudo service"

# vim (and some other stuff)
if [[ `uname` == "Darwin" ]];
then
	alias vim='mvim -v'
	alias   v='mvim -v'
	alias  vd="mvimdiff -v"
	alias  vo="mvim -v -O"

	alias unquarantine="xattr -r -d com.apple.quarantine *"

	# Tell ls to be colourful
	export CLICOLOR=1
	export LSCOLORS=Exfxcxdxbxegedabagacad

	# Tell grep to highlight matches
	export GREP_OPTIONS='--color=auto'

	export   PATH=/usr/local/bin:/usr/local/sbin:$PATH
	export EDITOR="mvim -v"
else
	alias  v="vim"
	alias vd="vimdiff"
	alias vo="vim -O"

	export   PATH="$HOME/Source/bash:$PATH"
	export EDITOR=vim
fi

for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
	alias "$method"="lwp-request -m '$method'"
done

# Private aliases
if [ -e ~/.zshrc-private ]
then
	source ~/.zshrc-private
fi

# Check for updates to Homebrew
BREW_UPDATE_FILE=~/.brew-update

function _update_brew_update()
{
	echo "BREW_UPDATE=`date +%s`" > $BREW_UPDATE_FILE
}

_update_brew_update

if [ -f $BREW_UPDATE_FILE ]
then
	. ~/.brew-update

	if [[ -z "$BREW_UPDATE" ]]; then
		_update_brew_update
	fi

	CURRENT_TIME=`date +%s`
	UPDATE_OFFSET=$((10 * 86400))
	NEXT_UPDATE=$(( CURRENT_TIME + UPDATE_OFFSET ))

	if [ $BREW_UPDATE -gt $NEXT_UPDATE ]
	then
		echo "[Homebrew] Would you like to check for updates?"
		echo "Type Y to update Homebrew: \c"
		read line
		if [ "$line" = Y ] || [ "$line" = y ]; then
			brew update
			brew upgrade
		fi

		_update_brew_update
	fi
else
	_update_brew_update
fi
