DOTFILES_BASE=$HOME/.dotfiles

export TERM="xterm-256color"
export KEYTIMEOUT=1

bindkey -v

# ZSH=$HOME/.oh-my-zsh
# 
# ZSH_THEME="joshtronic"
# 
# COMPLETION_WAITING_DOTS="true"
# 
# plugins=(brew common-aliases composer git-extras git gitfast gitignore jsontools meteor node npm nvm osx redis-cli rsync systemadmin vundle web-search xcode z zsh_reload)
# 
# source $ZSH/oh-my-zsh.sh

# PHP_FULL_VERSION=`php --version | head -n 1 | awk '{print $2}'`
# PHP_MAJOR_MINOR=`echo $PHP_FULL_VERSION | awk -F '.' '{print $1$2}'`
# PHP_BASE_PATH=/usr/local/Cellar/php$PHP_MAJOR_MINOR/$PHP_FULL_VERSION
# 
# export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$PHP_BASE_PATH/lib/php:~/Source/dotfiles/scripts:~/Source/dotfiles/git/scripts:$PHP_BASE_PATH/bin:/opt/X11/bin:$PHP_BASE_PATH/lib/php/File

source $DOTFILES_BASE/.antigen/antigen.zsh

antigen-use oh-my-zsh
antigen-bundle git

if [[ $OSTYPE == "darwin*" ]]; then
  antigen-bundle osx
fi

antigen-bundle zsh-users/zsh-completions
# antigen-bundle zsh-users/zsh-history-substring-search
antigen-bundle zsh-users/zsh-syntax-highlighting

antigen-theme $DOTFILES_BASE/zsh joshtronic
antigen-apply


# alias    gaa="git add --all"
# alias   gcob="git checkout -B"
# alias    gdb="git delete-branch"
# alias     gf="git fetch"
# alias    gmm="git merge master"
# alias   gmup="git fetch upstream; git merge origin/upstream"
# alias    gmv="git mv"
# #alias     gp="git rev-parse --abbrev-ref HEAD | xargs git push origin"
# #alias    gpu="git rev-parse --abbrev-ref HEAD | xargs git pull origin"
# alias    gra="git remote add"
# alias    grm="git rm"
# alias     gs="git status"
# alias gh-pages="bundle exec jekyll serve"
# alias    mtr="sudo mtr"
# alias   uuid="node -e \"var uuid = require('node-uuid'); console.log(uuid.v4())\""
# alias    unq="xattr -r -d com.apple.quarantine *"
# alias      v="vim"
# alias     vd="vimdiff"

export CLICOLOR=1
#export LSCOLORS=Exfxcxdxbxegedabagacad

export GREP_OPTIONS="--color=auto --exclude-dir=.git --exclude-dir=artwork --exclude-dir=node_modules --exclude-dir=.sass-cache"

export EDITOR=vim

for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "$method"="lwp-request -m '$method'"
done

export PATH=/usr/local/bin:/usr/local/sbin:./node_modules/bower/bin:./node_modules/grunt-cli/bin:$PATH

# source $(brew --prefix nvm)/nvm.sh

export NODE_ENV=development
