#!/bin/bash

if [[ $(pwd) == /Users/josh/Sites/* ]];
then
	osascript -e 'tell application "Safari"' \
	          -e 'activate' \
	          -e 'do javascript "if (location.href.substring(7, 12) == \"local\") { window.location.reload(); }" in first document' \
	          -e 'end tell' > /dev/null;
	osascript -e 'tell application "iTerm" to activate'
fi
